config/routes.rb
Rails.application.routes.draw do
  resources :todo_groups do
    resources :todo_tasks do
      member do
        patch :complete
      end
    end
  end
  
  root "todo_groups#index"
end

app/models/todo_group.rb
class TodoGroup < ActiveRecord::Base
  has_many :todo_tasks

  validates :title, :description, :presence => true
  validates :title, :length => { :maximum => 55}
  validates :description, :length => { :maximum => 140}
  validates :title, :uniqueness => true
end

app/models/todo_task.rb
class TodoTask < ActiveRecord::Base
  belongs_to :todo_group

  validates :content, :presence => true
  validates :content, :length => { :maximum => 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_groups_controller.rb
class TodoGroupsController < ApplicationController
  before_action :set_todo_group, only: [:show, :edit, :update, :destroy]

  def index
    @todo_groups = TodoGroup.all
  end

  def show
  end

  def new
    @todo_group = TodoGroup.new
  end

  def edit
  end

  def create
    @todo_group = TodoGroup.new(todo_group_params)

    respond_to do |format|
      if @todo_group.save
        format.html { redirect_to @todo_group }
        format.json { render :show, status: :created, location: @todo_group }
      else
        format.html { render :new }
        format.json { render json: @todo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_group.update(todo_group_params)
        format.html { redirect_to @todo_group }
        format.json { render :show, status: :ok, location: @todo_group }
      else
        format.html { render :edit }
        format.json { render json: @todo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_group.destroy
    respond_to do |format|
      format.html { redirect_to todo_groups_url}
      format.json { head :no_content }
    end
  end

  private
    def set_todo_group
      @todo_group = TodoGroup.find(params[:id])
    end

    def todo_group_params
      params.require(:todo_group).permit(:title, :description)
    end
end

app/controllers/todo_tasks_controller.rb
class TodoTasksController < ApplicationController
  before_action :declare_todo_group
  before_action :declare_todo_task, except: [:create]

  def create
    @todo_task = @todo_group.todo_tasks.create(todo_task_params)
    @todo_task.update_attribute(:completed, false)
    redirect_to @todo_group
  end

  def destroy
    @todo_task = @todo_group.todo_tasks.find(params[:id])
    if @todo_task.destroy
      redirect_to @todo_group
    else
      redirect_to @todo_group
    end
  end

  def complete
    if @todo_task.completed?
      @todo_task.update_attribute(:completed, false)
    else
      @todo_task.update_attribute(:completed, true)
    end
    redirect_to @todo_group
  end

  private

    def declare_todo_group
      @todo_group = TodoGroup.find(params[:todo_group_id])
    end

    def todo_task_params
      params[:todo_task].permit(:content, :completed)
    end

    def declare_todo_task
      @todo_task = TodoTask.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_groups_helper.rb
module TodoGroupsHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,400,700,900" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_groups/_form.html.erb
<%= form_for(@todo_group) do |f| %>
  <% if @todo_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_group.errors.count, "error") %> prohibited this todo_group from being saved:</h2>

      <ul>
      <% @todo_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Description"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_groups/edit.html.erb
<div class="group_form">
  <h1>Edit Group</h1>
    <%= render 'form' %>

    <%= link_to 'Show', @todo_group %> |
    <%= link_to 'Back', todo_groups_path %>
</div>

app/views/todo_groups/index.html.erb
<div class="groups_wrapper">
  <h1>ToDo Groups</h1>
  <% @todo_groups.each do |todo_group| %>
    <%= link_to todo_group do %>
      <div class="task">
        <h2><%= todo_group.title %></h2>
        <p><%= todo_group.description %></p>
        <div class="tasks_size">
          <p><%= pluralize(todo_group.todo_tasks.size, "Task") %></p>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="new_group_link">
    <%= link_to 'New Task Group', new_todo_group_path %>
  </div>

  <div class="created_by">
    Created by <a href="http://melvinhernandez.github.io">MelvinHernandez</a>
  </div>
</div>

app/views/todo_groups/new.html.erb
<div class="group_form">
  <h1>New Group</h1>

  <%= render 'form' %>

  <%= link_to 'Back', todo_groups_path %>
</div>

app/views/todo_groups/show.html.erb
<div class="groups_wrapper">

  <h1 class="task_group_title">
    <%= @todo_group.title %>
  </h1>
  <h3>
    <%= @todo_group.description %>
  </h3>
  <div class="tasks-n-form">
    <div id="todo_tasks_wrapper">
      <div id="todo_tasks_container">
        <%= render @todo_group.todo_tasks %>
      </div>
    </div>
    <div id="todo_task_form">
      <%= render "todo_tasks/form" %>
    </div>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="group_meta_links">
    <%= link_to 'Back', todo_groups_path %> |
    <%= link_to 'Edit', edit_todo_group_path(@todo_group) %> |
    <%= link_to 'Delete', todo_group_path, method: :delete, data: { confirm: 'Are you sure you want to delete this entire group?' } %>
  </div>
</div>

app/views/todo_tasks/_form.html.erb
<%= form_for([@todo_group, @todo_group.todo_tasks.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New ToDo Task" %>
  <%= f.submit "New Task"%>
<% end %>

app/views/todo_tasks/_todo_task.html.erb
<div  class="task_content">
  <% if todo_task.completed? %>
    <%= link_to complete_todo_group_todo_task_path(@todo_group, todo_task.id), method: :patch, class: "check_link"  do%>
      <i class="fa fa-check-circle-o" aria-hidden="true"></i>
    <% end %>
    <p class="task_blob completed_blob"><%= todo_task.content %></p>
  <% else %>
    <%= link_to complete_todo_group_todo_task_path(@todo_group, todo_task.id), method: :patch, class: "check_link"  do%>
      <i class="fa fa-circle-o" aria-hidden="true"></i>
    <% end %>
    <div class="task_blob"><%= todo_task.content %></div>
  <% end %>
  <%= link_to todo_group_todo_task_path(@todo_group, todo_task.id), method: :delete, data: {confirm: "Are you sure you want to delete this Task?"}, class: "delete_link" do %>
    <i class="fa fa-trash-o" aria-hidden="true"></i>
  <% end %>
</div>